__description__ = 'jokegetter'
__url__ = 'https://github.com/afaucon/jokegetter'
__version__ = '1.0.0'
__author__ = 'Adrien Faucon'
__author_email__ = 'adrien.faucon@gmail.com'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2019 Adrien Faucon'
